table location_data
	lineageTag: ff0a9905-1efc-4eaf-8235-11d3ca55e230

	column LocationID
		dataType: string
		lineageTag: 53c80e25-e78b-429a-9ad2-83304b556abe
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 43d50a83-6e45-4401-9038-6b023b4aca97
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 02aa92bf-f7d5-494e-80b0-4f2f1ad3adea
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e0faa4c7-eea9-4582-8d87-195f58478dcb
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Zipcode
		dataType: string
		lineageTag: be67a537-702b-4955-b9e3-9fa73af5f356
		summarizeBy: none
		sourceColumn: Zipcode

		annotation SummarizationSetBy = Automatic

	partition location_data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\DAHMAD\Downloads\FinalSupplyChain\Supply_B\supply_chain_data_raw\location_data.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"LocationID", type text}, {"Country", type text}, {"State", type text}, {"City", type text}, {"Zipcode", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

